version: 2
jobs:
 build:
   machine: true
   steps:
     - checkout 

     # build image
     - run: |
         echo -e "NODE_ENV=$NODE_ENV \nPORT=$PORT \nMONGOLAB_URI=$MONGOLAB_URI" >> .env         
         docker info
         docker build -t nodeapp -f Dockerfile .
     # deploy the image
     - run: |         
         docker login --username=$HEROKU_USERNAME --password=$HEROKU_API_KEY registry.heroku.com
         docker tag nodeapp registry.heroku.com/$HEROKU_APP_NAME/web
         docker push registry.heroku.com/$HEROKU_APP_NAME/web                
         curl https://cli-assets.heroku.com/install.sh | sh
         heroku container:release web -a $HEROKU_APP_NAME